package com.perfect.githubexplorer

import com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory
import com.perfect.githubexplorer.data.*
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkObject
import io.mockk.mockkStatic
import kotlinx.coroutines.Deferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import org.junit.Test
import retrofit2.mock.MockRetrofit
import org.junit.Assert.*
import org.junit.Before
import retrofit2.http.GET
import retrofit2.http.Query
import retrofit2.mock.BehaviorDelegate
import retrofit2.mock.NetworkBehavior
import java.util.Collections.emptyList
import java.util.concurrent.TimeUnit
import okhttp3.mockwebserver.MockWebServer
import okhttp3.HttpUrl
import okhttp3.mockwebserver.MockResponse
import org.junit.After
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

const val RESPONSE_JSON = """{
"total_count": 14978,
"incomplete_results": false,
"items": [
{
"id": 892275,
"node_id": "MDEwOlJlcG9zaXRvcnk4OTIyNzU=",
"name": "retrofit",
"full_name": "square/retrofit",
"private": false,
"owner": {
"login": "square",
"id": 82592,
"node_id": "MDEyOk9yZ2FuaXphdGlvbjgyNTky",
"avatar_url": "https://avatars0.githubusercontent.com/u/82592?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/square",
"html_url": "https://github.com/square",
"followers_url": "https://api.github.com/users/square/followers",
"following_url": "https://api.github.com/users/square/following{/other_user}",
"gists_url": "https://api.github.com/users/square/gists{/gist_id}",
"starred_url": "https://api.github.com/users/square/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/square/subscriptions",
"organizations_url": "https://api.github.com/users/square/orgs",
"repos_url": "https://api.github.com/users/square/repos",
"events_url": "https://api.github.com/users/square/events{/privacy}",
"received_events_url": "https://api.github.com/users/square/received_events",
"type": "Organization",
"site_admin": false
},
"html_url": "https://github.com/square/retrofit",
"description": "Type-safe HTTP client for Android and Java by Square, Inc.",
"fork": false,
"url": "https://api.github.com/repos/square/retrofit",
"forks_url": "https://api.github.com/repos/square/retrofit/forks",
"keys_url": "https://api.github.com/repos/square/retrofit/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/square/retrofit/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/square/retrofit/teams",
"hooks_url": "https://api.github.com/repos/square/retrofit/hooks",
"issue_events_url": "https://api.github.com/repos/square/retrofit/issues/events{/number}",
"events_url": "https://api.github.com/repos/square/retrofit/events",
"assignees_url": "https://api.github.com/repos/square/retrofit/assignees{/user}",
"branches_url": "https://api.github.com/repos/square/retrofit/branches{/branch}",
"tags_url": "https://api.github.com/repos/square/retrofit/tags",
"blobs_url": "https://api.github.com/repos/square/retrofit/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/square/retrofit/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/square/retrofit/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/square/retrofit/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/square/retrofit/statuses/{sha}",
"languages_url": "https://api.github.com/repos/square/retrofit/languages",
"stargazers_url": "https://api.github.com/repos/square/retrofit/stargazers",
"contributors_url": "https://api.github.com/repos/square/retrofit/contributors",
"subscribers_url": "https://api.github.com/repos/square/retrofit/subscribers",
"subscription_url": "https://api.github.com/repos/square/retrofit/subscription",
"commits_url": "https://api.github.com/repos/square/retrofit/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/square/retrofit/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/square/retrofit/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/square/retrofit/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/square/retrofit/contents/{+path}",
"compare_url": "https://api.github.com/repos/square/retrofit/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/square/retrofit/merges",
"archive_url": "https://api.github.com/repos/square/retrofit/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/square/retrofit/downloads",
"issues_url": "https://api.github.com/repos/square/retrofit/issues{/number}",
"pulls_url": "https://api.github.com/repos/square/retrofit/pulls{/number}",
"milestones_url": "https://api.github.com/repos/square/retrofit/milestones{/number}",
"notifications_url": "https://api.github.com/repos/square/retrofit/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/square/retrofit/labels{/name}",
"releases_url": "https://api.github.com/repos/square/retrofit/releases{/id}",
"deployments_url": "https://api.github.com/repos/square/retrofit/deployments",
"created_at": "2010-09-06T21:39:43Z",
"updated_at": "2019-02-25T09:47:58Z",
"pushed_at": "2019-02-25T00:37:10Z",
"git_url": "git://github.com/square/retrofit.git",
"ssh_url": "git@github.com:square/retrofit.git",
"clone_url": "https://github.com/square/retrofit.git",
"svn_url": "https://github.com/square/retrofit",
"homepage": "http://square.github.io/retrofit/",
"size": 4910,
"stargazers_count": 31349,
"watchers_count": 31349,
"language": "Java",
"has_issues": true,
"has_projects": false,
"has_downloads": true,
"has_wiki": true,
"has_pages": true,
"forks_count": 5879,
"mirror_url": null,
"archived": false,
"open_issues_count": 63,
"license": {
"key": "apache-2.0",
"name": "Apache License 2.0",
"spdx_id": "Apache-2.0",
"url": "https://api.github.com/licenses/apache-2.0",
"node_id": "MDc6TGljZW5zZTI="
},
"forks": 5879,
"open_issues": 63,
"watchers": 31349,
"default_branch": "master",
"score": 166.65593
},
{
"id": 62875403,
"node_id": "MDEwOlJlcG9zaXRvcnk2Mjg3NTQwMw==",
"name": "RetrofitClient",
"full_name": "Tamicer/RetrofitClient",
"private": false,
"owner": {
"login": "Tamicer",
"id": 13105459,
"node_id": "MDQ6VXNlcjEzMTA1NDU5",
"avatar_url": "https://avatars1.githubusercontent.com/u/13105459?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Tamicer",
"html_url": "https://github.com/Tamicer",
"followers_url": "https://api.github.com/users/Tamicer/followers",
"following_url": "https://api.github.com/users/Tamicer/following{/other_user}",
"gists_url": "https://api.github.com/users/Tamicer/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Tamicer/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Tamicer/subscriptions",
"organizations_url": "https://api.github.com/users/Tamicer/orgs",
"repos_url": "https://api.github.com/users/Tamicer/repos",
"events_url": "https://api.github.com/users/Tamicer/events{/privacy}",
"received_events_url": "https://api.github.com/users/Tamicer/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/Tamicer/RetrofitClient",
"description": "基于Retrofit2.x和Rxjava2.x封装的请求工具类(内含Retrofit2.x & rxjava1.x)",
"fork": false,
"url": "https://api.github.com/repos/Tamicer/RetrofitClient",
"forks_url": "https://api.github.com/repos/Tamicer/RetrofitClient/forks",
"keys_url": "https://api.github.com/repos/Tamicer/RetrofitClient/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/Tamicer/RetrofitClient/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/Tamicer/RetrofitClient/teams",
"hooks_url": "https://api.github.com/repos/Tamicer/RetrofitClient/hooks",
"issue_events_url": "https://api.github.com/repos/Tamicer/RetrofitClient/issues/events{/number}",
"events_url": "https://api.github.com/repos/Tamicer/RetrofitClient/events",
"assignees_url": "https://api.github.com/repos/Tamicer/RetrofitClient/assignees{/user}",
"branches_url": "https://api.github.com/repos/Tamicer/RetrofitClient/branches{/branch}",
"tags_url": "https://api.github.com/repos/Tamicer/RetrofitClient/tags",
"blobs_url": "https://api.github.com/repos/Tamicer/RetrofitClient/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/Tamicer/RetrofitClient/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/Tamicer/RetrofitClient/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/Tamicer/RetrofitClient/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/Tamicer/RetrofitClient/statuses/{sha}",
"languages_url": "https://api.github.com/repos/Tamicer/RetrofitClient/languages",
"stargazers_url": "https://api.github.com/repos/Tamicer/RetrofitClient/stargazers",
"contributors_url": "https://api.github.com/repos/Tamicer/RetrofitClient/contributors",
"subscribers_url": "https://api.github.com/repos/Tamicer/RetrofitClient/subscribers",
"subscription_url": "https://api.github.com/repos/Tamicer/RetrofitClient/subscription",
"commits_url": "https://api.github.com/repos/Tamicer/RetrofitClient/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/Tamicer/RetrofitClient/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/Tamicer/RetrofitClient/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/Tamicer/RetrofitClient/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/Tamicer/RetrofitClient/contents/{+path}",
"compare_url": "https://api.github.com/repos/Tamicer/RetrofitClient/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/Tamicer/RetrofitClient/merges",
"archive_url": "https://api.github.com/repos/Tamicer/RetrofitClient/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/Tamicer/RetrofitClient/downloads",
"issues_url": "https://api.github.com/repos/Tamicer/RetrofitClient/issues{/number}",
"pulls_url": "https://api.github.com/repos/Tamicer/RetrofitClient/pulls{/number}",
"milestones_url": "https://api.github.com/repos/Tamicer/RetrofitClient/milestones{/number}",
"notifications_url": "https://api.github.com/repos/Tamicer/RetrofitClient/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/Tamicer/RetrofitClient/labels{/name}",
"releases_url": "https://api.github.com/repos/Tamicer/RetrofitClient/releases{/id}",
"deployments_url": "https://api.github.com/repos/Tamicer/RetrofitClient/deployments",
"created_at": "2016-07-08T09:08:17Z",
"updated_at": "2019-02-20T06:23:04Z",
"pushed_at": "2017-12-13T12:02:47Z",
"git_url": "git://github.com/Tamicer/RetrofitClient.git",
"ssh_url": "git@github.com:Tamicer/RetrofitClient.git",
"clone_url": "https://github.com/Tamicer/RetrofitClient.git",
"svn_url": "https://github.com/Tamicer/RetrofitClient",
"homepage": "",
"size": 287,
"stargazers_count": 490,
"watchers_count": 490,
"language": "Java",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 155,
"mirror_url": null,
"archived": false,
"open_issues_count": 1,
"license": {
"key": "apache-2.0",
"name": "Apache License 2.0",
"spdx_id": "Apache-2.0",
"url": "https://api.github.com/licenses/apache-2.0",
"node_id": "MDc6TGljZW5zZTI="
},
"forks": 155,
"open_issues": 1,
"watchers": 490,
"default_branch": "master",
"score": 108.56195
},
{
"id": 97385710,
"node_id": "MDEwOlJlcG9zaXRvcnk5NzM4NTcxMA==",
"name": "RetrofitUrlManager",
"full_name": "JessYanCoding/RetrofitUrlManager",
"private": false,
"owner": {
"login": "JessYanCoding",
"id": 15711968,
"node_id": "MDQ6VXNlcjE1NzExOTY4",
"avatar_url": "https://avatars2.githubusercontent.com/u/15711968?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/JessYanCoding",
"html_url": "https://github.com/JessYanCoding",
"followers_url": "https://api.github.com/users/JessYanCoding/followers",
"following_url": "https://api.github.com/users/JessYanCoding/following{/other_user}",
"gists_url": "https://api.github.com/users/JessYanCoding/gists{/gist_id}",
"starred_url": "https://api.github.com/users/JessYanCoding/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/JessYanCoding/subscriptions",
"organizations_url": "https://api.github.com/users/JessYanCoding/orgs",
"repos_url": "https://api.github.com/users/JessYanCoding/repos",
"events_url": "https://api.github.com/users/JessYanCoding/events{/privacy}",
"received_events_url": "https://api.github.com/users/JessYanCoding/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/JessYanCoding/RetrofitUrlManager",
"description": "🔮 Let Retrofit support multiple baseUrl and can be change the baseUrl at runtime (以最简洁的 Api 让 Retrofit 同时支持多个 BaseUrl 以及动态改变 BaseUrl).",
"fork": false,
"url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager",
"forks_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/forks",
"keys_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/teams",
"hooks_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/hooks",
"issue_events_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/issues/events{/number}",
"events_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/events",
"assignees_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/assignees{/user}",
"branches_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/branches{/branch}",
"tags_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/tags",
"blobs_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/statuses/{sha}",
"languages_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/languages",
"stargazers_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/stargazers",
"contributors_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/contributors",
"subscribers_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/subscribers",
"subscription_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/subscription",
"commits_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/contents/{+path}",
"compare_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/merges",
"archive_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/downloads",
"issues_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/issues{/number}",
"pulls_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/pulls{/number}",
"milestones_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/milestones{/number}",
"notifications_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/labels{/name}",
"releases_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/releases{/id}",
"deployments_url": "https://api.github.com/repos/JessYanCoding/RetrofitUrlManager/deployments",
"created_at": "2017-07-16T13:37:29Z",
"updated_at": "2019-02-25T08:03:38Z",
"pushed_at": "2018-11-14T07:38:55Z",
"git_url": "git://github.com/JessYanCoding/RetrofitUrlManager.git",
"ssh_url": "git@github.com:JessYanCoding/RetrofitUrlManager.git",
"clone_url": "https://github.com/JessYanCoding/RetrofitUrlManager.git",
"svn_url": "https://github.com/JessYanCoding/RetrofitUrlManager",
"homepage": "",
"size": 16160,
"stargazers_count": 1053,
"watchers_count": 1053,
"language": "Java",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 136,
"mirror_url": null,
"archived": false,
"open_issues_count": 2,
"license": {
"key": "apache-2.0",
"name": "Apache License 2.0",
"spdx_id": "Apache-2.0",
"url": "https://api.github.com/licenses/apache-2.0",
"node_id": "MDc6TGljZW5zZTI="
},
"forks": 136,
"open_issues": 2,
"watchers": 1053,
"default_branch": "master",
"score": 107.04232
},
{
"id": 56908418,
"node_id": "MDEwOlJlcG9zaXRvcnk1NjkwODQxOA==",
"name": "Retrofit2Demo",
"full_name": "ikidou/Retrofit2Demo",
"private": false,
"owner": {
"login": "ikidou",
"id": 10000055,
"node_id": "MDQ6VXNlcjEwMDAwMDU1",
"avatar_url": "https://avatars0.githubusercontent.com/u/10000055?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/ikidou",
"html_url": "https://github.com/ikidou",
"followers_url": "https://api.github.com/users/ikidou/followers",
"following_url": "https://api.github.com/users/ikidou/following{/other_user}",
"gists_url": "https://api.github.com/users/ikidou/gists{/gist_id}",
"starred_url": "https://api.github.com/users/ikidou/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/ikidou/subscriptions",
"organizations_url": "https://api.github.com/users/ikidou/orgs",
"repos_url": "https://api.github.com/users/ikidou/repos",
"events_url": "https://api.github.com/users/ikidou/events{/privacy}",
"received_events_url": "https://api.github.com/users/ikidou/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/ikidou/Retrofit2Demo",
"description": null,
"fork": false,
"url": "https://api.github.com/repos/ikidou/Retrofit2Demo",
"forks_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/forks",
"keys_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/teams",
"hooks_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/hooks",
"issue_events_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/issues/events{/number}",
"events_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/events",
"assignees_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/assignees{/user}",
"branches_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/branches{/branch}",
"tags_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/tags",
"blobs_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/statuses/{sha}",
"languages_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/languages",
"stargazers_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/stargazers",
"contributors_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/contributors",
"subscribers_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/subscribers",
"subscription_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/subscription",
"commits_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/contents/{+path}",
"compare_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/merges",
"archive_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/downloads",
"issues_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/issues{/number}",
"pulls_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/pulls{/number}",
"milestones_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/milestones{/number}",
"notifications_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/labels{/name}",
"releases_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/releases{/id}",
"deployments_url": "https://api.github.com/repos/ikidou/Retrofit2Demo/deployments",
"created_at": "2016-04-23T08:18:27Z",
"updated_at": "2019-02-18T06:13:14Z",
"pushed_at": "2018-06-01T10:39:34Z",
"git_url": "git://github.com/ikidou/Retrofit2Demo.git",
"ssh_url": "git@github.com:ikidou/Retrofit2Demo.git",
"clone_url": "https://github.com/ikidou/Retrofit2Demo.git",
"svn_url": "https://github.com/ikidou/Retrofit2Demo",
"homepage": null,
"size": 263,
"stargazers_count": 346,
"watchers_count": 346,
"language": "Java",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 147,
"mirror_url": null,
"archived": false,
"open_issues_count": 1,
"license": null,
"forks": 147,
"open_issues": 1,
"watchers": 346,
"default_branch": "master",
"score": 102.31651
},
{
"id": 115532492,
"node_id": "MDEwOlJlcG9zaXRvcnkxMTU1MzI0OTI=",
"name": "retrofit2-kotlin-coroutines-adapter",
"full_name": "JakeWharton/retrofit2-kotlin-coroutines-adapter",
"private": false,
"owner": {
"login": "JakeWharton",
"id": 66577,
"node_id": "MDQ6VXNlcjY2NTc3",
"avatar_url": "https://avatars0.githubusercontent.com/u/66577?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/JakeWharton",
"html_url": "https://github.com/JakeWharton",
"followers_url": "https://api.github.com/users/JakeWharton/followers",
"following_url": "https://api.github.com/users/JakeWharton/following{/other_user}",
"gists_url": "https://api.github.com/users/JakeWharton/gists{/gist_id}",
"starred_url": "https://api.github.com/users/JakeWharton/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/JakeWharton/subscriptions",
"organizations_url": "https://api.github.com/users/JakeWharton/orgs",
"repos_url": "https://api.github.com/users/JakeWharton/repos",
"events_url": "https://api.github.com/users/JakeWharton/events{/privacy}",
"received_events_url": "https://api.github.com/users/JakeWharton/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter",
"description": "A Retrofit 2 adapter for Kotlin coroutine's Deferred type.",
"fork": false,
"url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter",
"forks_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/forks",
"keys_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/teams",
"hooks_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/hooks",
"issue_events_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/issues/events{/number}",
"events_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/events",
"assignees_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/assignees{/user}",
"branches_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/branches{/branch}",
"tags_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/tags",
"blobs_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/statuses/{sha}",
"languages_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/languages",
"stargazers_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/stargazers",
"contributors_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/contributors",
"subscribers_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/subscribers",
"subscription_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/subscription",
"commits_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/contents/{+path}",
"compare_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/merges",
"archive_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/downloads",
"issues_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/issues{/number}",
"pulls_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/pulls{/number}",
"milestones_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/milestones{/number}",
"notifications_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/labels{/name}",
"releases_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/releases{/id}",
"deployments_url": "https://api.github.com/repos/JakeWharton/retrofit2-kotlin-coroutines-adapter/deployments",
"created_at": "2017-12-27T15:10:17Z",
"updated_at": "2019-02-23T19:20:03Z",
"pushed_at": "2018-12-19T19:13:39Z",
"git_url": "git://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter.git",
"ssh_url": "git@github.com:JakeWharton/retrofit2-kotlin-coroutines-adapter.git",
"clone_url": "https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter.git",
"svn_url": "https://github.com/JakeWharton/retrofit2-kotlin-coroutines-adapter",
"homepage": null,
"size": 136,
"stargazers_count": 1369,
"watchers_count": 1369,
"language": "Kotlin",
"has_issues": true,
"has_projects": false,
"has_downloads": true,
"has_wiki": false,
"has_pages": false,
"forks_count": 72,
"mirror_url": null,
"archived": false,
"open_issues_count": 9,
"license": {
"key": "apache-2.0",
"name": "Apache License 2.0",
"spdx_id": "Apache-2.0",
"url": "https://api.github.com/licenses/apache-2.0",
"node_id": "MDc6TGljZW5zZTI="
},
"forks": 72,
"open_issues": 9,
"watchers": 1369,
"default_branch": "master",
"score": 98.28414
},
{
"id": 53483065,
"node_id": "MDEwOlJlcG9zaXRvcnk1MzQ4MzA2NQ==",
"name": "RxjavaRetrofitDemo",
"full_name": "tough1985/RxjavaRetrofitDemo",
"private": false,
"owner": {
"login": "tough1985",
"id": 3264723,
"node_id": "MDQ6VXNlcjMyNjQ3MjM=",
"avatar_url": "https://avatars2.githubusercontent.com/u/3264723?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/tough1985",
"html_url": "https://github.com/tough1985",
"followers_url": "https://api.github.com/users/tough1985/followers",
"following_url": "https://api.github.com/users/tough1985/following{/other_user}",
"gists_url": "https://api.github.com/users/tough1985/gists{/gist_id}",
"starred_url": "https://api.github.com/users/tough1985/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/tough1985/subscriptions",
"organizations_url": "https://api.github.com/users/tough1985/orgs",
"repos_url": "https://api.github.com/users/tough1985/repos",
"events_url": "https://api.github.com/users/tough1985/events{/privacy}",
"received_events_url": "https://api.github.com/users/tough1985/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/tough1985/RxjavaRetrofitDemo",
"description": "A demo show how to use Retrofit with Rxjava",
"fork": false,
"url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo",
"forks_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/forks",
"keys_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/teams",
"hooks_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/hooks",
"issue_events_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/issues/events{/number}",
"events_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/events",
"assignees_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/assignees{/user}",
"branches_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/branches{/branch}",
"tags_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/tags",
"blobs_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/statuses/{sha}",
"languages_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/languages",
"stargazers_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/stargazers",
"contributors_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/contributors",
"subscribers_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/subscribers",
"subscription_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/subscription",
"commits_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/contents/{+path}",
"compare_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/merges",
"archive_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/downloads",
"issues_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/issues{/number}",
"pulls_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/pulls{/number}",
"milestones_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/milestones{/number}",
"notifications_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/labels{/name}",
"releases_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/releases{/id}",
"deployments_url": "https://api.github.com/repos/tough1985/RxjavaRetrofitDemo/deployments",
"created_at": "2016-03-09T08:57:41Z",
"updated_at": "2019-02-19T03:03:02Z",
"pushed_at": "2016-11-16T07:37:31Z",
"git_url": "git://github.com/tough1985/RxjavaRetrofitDemo.git",
"ssh_url": "git@github.com:tough1985/RxjavaRetrofitDemo.git",
"clone_url": "https://github.com/tough1985/RxjavaRetrofitDemo.git",
"svn_url": "https://github.com/tough1985/RxjavaRetrofitDemo",
"homepage": "",
"size": 137,
"stargazers_count": 1261,
"watchers_count": 1261,
"language": "Java",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 320,
"mirror_url": null,
"archived": false,
"open_issues_count": 12,
"license": {
"key": "mit",
"name": "MIT License",
"spdx_id": "MIT",
"url": "https://api.github.com/licenses/mit",
"node_id": "MDc6TGljZW5zZTEz"
},
"forks": 320,
"open_issues": 12,
"watchers": 1261,
"default_branch": "master",
"score": 97.73569
},
{
"id": 63559858,
"node_id": "MDEwOlJlcG9zaXRvcnk2MzU1OTg1OA==",
"name": "RxjavaRetrofitDemo-master",
"full_name": "wzgiceman/RxjavaRetrofitDemo-master",
"private": false,
"owner": {
"login": "wzgiceman",
"id": 3830012,
"node_id": "MDQ6VXNlcjM4MzAwMTI=",
"avatar_url": "https://avatars2.githubusercontent.com/u/3830012?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/wzgiceman",
"html_url": "https://github.com/wzgiceman",
"followers_url": "https://api.github.com/users/wzgiceman/followers",
"following_url": "https://api.github.com/users/wzgiceman/following{/other_user}",
"gists_url": "https://api.github.com/users/wzgiceman/gists{/gist_id}",
"starred_url": "https://api.github.com/users/wzgiceman/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/wzgiceman/subscriptions",
"organizations_url": "https://api.github.com/users/wzgiceman/orgs",
"repos_url": "https://api.github.com/users/wzgiceman/repos",
"events_url": "https://api.github.com/users/wzgiceman/events{/privacy}",
"received_events_url": "https://api.github.com/users/wzgiceman/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/wzgiceman/RxjavaRetrofitDemo-master",
"description": "Retrofit+Rxjava+okhttp终极封装(Gson方案)",
"fork": false,
"url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master",
"forks_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/forks",
"keys_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/teams",
"hooks_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/hooks",
"issue_events_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/issues/events{/number}",
"events_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/events",
"assignees_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/assignees{/user}",
"branches_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/branches{/branch}",
"tags_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/tags",
"blobs_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/statuses/{sha}",
"languages_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/languages",
"stargazers_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/stargazers",
"contributors_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/contributors",
"subscribers_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/subscribers",
"subscription_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/subscription",
"commits_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/contents/{+path}",
"compare_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/merges",
"archive_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/downloads",
"issues_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/issues{/number}",
"pulls_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/pulls{/number}",
"milestones_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/milestones{/number}",
"notifications_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/labels{/name}",
"releases_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/releases{/id}",
"deployments_url": "https://api.github.com/repos/wzgiceman/RxjavaRetrofitDemo-master/deployments",
"created_at": "2016-07-18T01:01:44Z",
"updated_at": "2019-02-25T10:05:55Z",
"pushed_at": "2018-04-20T01:40:49Z",
"git_url": "git://github.com/wzgiceman/RxjavaRetrofitDemo-master.git",
"ssh_url": "git@github.com:wzgiceman/RxjavaRetrofitDemo-master.git",
"clone_url": "https://github.com/wzgiceman/RxjavaRetrofitDemo-master.git",
"svn_url": "https://github.com/wzgiceman/RxjavaRetrofitDemo-master",
"homepage": "http://blog.csdn.net/column/details/13297.html",
"size": 3837,
"stargazers_count": 874,
"watchers_count": 874,
"language": "Java",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 261,
"mirror_url": null,
"archived": false,
"open_issues_count": 27,
"license": {
"key": "mit",
"name": "MIT License",
"spdx_id": "MIT",
"url": "https://api.github.com/licenses/mit",
"node_id": "MDc6TGljZW5zZTEz"
},
"forks": 261,
"open_issues": 27,
"watchers": 874,
"default_branch": "master",
"score": 94.14076
},
{
"id": 65788592,
"node_id": "MDEwOlJlcG9zaXRvcnk2NTc4ODU5Mg==",
"name": "retrofit2-rxjava2-adapter",
"full_name": "JakeWharton/retrofit2-rxjava2-adapter",
"private": false,
"owner": {
"login": "JakeWharton",
"id": 66577,
"node_id": "MDQ6VXNlcjY2NTc3",
"avatar_url": "https://avatars0.githubusercontent.com/u/66577?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/JakeWharton",
"html_url": "https://github.com/JakeWharton",
"followers_url": "https://api.github.com/users/JakeWharton/followers",
"following_url": "https://api.github.com/users/JakeWharton/following{/other_user}",
"gists_url": "https://api.github.com/users/JakeWharton/gists{/gist_id}",
"starred_url": "https://api.github.com/users/JakeWharton/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/JakeWharton/subscriptions",
"organizations_url": "https://api.github.com/users/JakeWharton/orgs",
"repos_url": "https://api.github.com/users/JakeWharton/repos",
"events_url": "https://api.github.com/users/JakeWharton/events{/privacy}",
"received_events_url": "https://api.github.com/users/JakeWharton/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/JakeWharton/retrofit2-rxjava2-adapter",
"description": "An RxJava 2 CallAdapter.Factory implementation for Retrofit 2.",
"fork": false,
"url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter",
"forks_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/forks",
"keys_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/teams",
"hooks_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/hooks",
"issue_events_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/issues/events{/number}",
"events_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/events",
"assignees_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/assignees{/user}",
"branches_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/branches{/branch}",
"tags_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/tags",
"blobs_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/statuses/{sha}",
"languages_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/languages",
"stargazers_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/stargazers",
"contributors_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/contributors",
"subscribers_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/subscribers",
"subscription_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/subscription",
"commits_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/contents/{+path}",
"compare_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/merges",
"archive_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/downloads",
"issues_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/issues{/number}",
"pulls_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/pulls{/number}",
"milestones_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/milestones{/number}",
"notifications_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/labels{/name}",
"releases_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/releases{/id}",
"deployments_url": "https://api.github.com/repos/JakeWharton/retrofit2-rxjava2-adapter/deployments",
"created_at": "2016-08-16T04:53:06Z",
"updated_at": "2019-02-23T08:34:46Z",
"pushed_at": "2017-02-21T22:34:22Z",
"git_url": "git://github.com/JakeWharton/retrofit2-rxjava2-adapter.git",
"ssh_url": "git@github.com:JakeWharton/retrofit2-rxjava2-adapter.git",
"clone_url": "https://github.com/JakeWharton/retrofit2-rxjava2-adapter.git",
"svn_url": "https://github.com/JakeWharton/retrofit2-rxjava2-adapter",
"homepage": "",
"size": 45,
"stargazers_count": 817,
"watchers_count": 817,
"language": null,
"has_issues": false,
"has_projects": true,
"has_downloads": true,
"has_wiki": false,
"has_pages": false,
"forks_count": 63,
"mirror_url": null,
"archived": false,
"open_issues_count": 0,
"license": null,
"forks": 63,
"open_issues": 0,
"watchers": 817,
"default_branch": "master",
"score": 93.97572
},
{
"id": 24766171,
"node_id": "MDEwOlJlcG9zaXRvcnkyNDc2NjE3MQ==",
"name": "RetrofitExample",
"full_name": "traex/RetrofitExample",
"private": false,
"owner": {
"login": "traex",
"id": 3145083,
"node_id": "MDQ6VXNlcjMxNDUwODM=",
"avatar_url": "https://avatars1.githubusercontent.com/u/3145083?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/traex",
"html_url": "https://github.com/traex",
"followers_url": "https://api.github.com/users/traex/followers",
"following_url": "https://api.github.com/users/traex/following{/other_user}",
"gists_url": "https://api.github.com/users/traex/gists{/gist_id}",
"starred_url": "https://api.github.com/users/traex/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/traex/subscriptions",
"organizations_url": "https://api.github.com/users/traex/orgs",
"repos_url": "https://api.github.com/users/traex/repos",
"events_url": "https://api.github.com/users/traex/events{/privacy}",
"received_events_url": "https://api.github.com/users/traex/received_events",
"type": "User",
"site_admin": false
},
"html_url": "https://github.com/traex/RetrofitExample",
"description": "Example for one of my tutorials at http://blog.robinchutaux.com/blog/a-smart-way-to-use-retrofit/",
"fork": false,
"url": "https://api.github.com/repos/traex/RetrofitExample",
"forks_url": "https://api.github.com/repos/traex/RetrofitExample/forks",
"keys_url": "https://api.github.com/repos/traex/RetrofitExample/keys{/key_id}",
"collaborators_url": "https://api.github.com/repos/traex/RetrofitExample/collaborators{/collaborator}",
"teams_url": "https://api.github.com/repos/traex/RetrofitExample/teams",
"hooks_url": "https://api.github.com/repos/traex/RetrofitExample/hooks",
"issue_events_url": "https://api.github.com/repos/traex/RetrofitExample/issues/events{/number}",
"events_url": "https://api.github.com/repos/traex/RetrofitExample/events",
"assignees_url": "https://api.github.com/repos/traex/RetrofitExample/assignees{/user}",
"branches_url": "https://api.github.com/repos/traex/RetrofitExample/branches{/branch}",
"tags_url": "https://api.github.com/repos/traex/RetrofitExample/tags",
"blobs_url": "https://api.github.com/repos/traex/RetrofitExample/git/blobs{/sha}",
"git_tags_url": "https://api.github.com/repos/traex/RetrofitExample/git/tags{/sha}",
"git_refs_url": "https://api.github.com/repos/traex/RetrofitExample/git/refs{/sha}",
"trees_url": "https://api.github.com/repos/traex/RetrofitExample/git/trees{/sha}",
"statuses_url": "https://api.github.com/repos/traex/RetrofitExample/statuses/{sha}",
"languages_url": "https://api.github.com/repos/traex/RetrofitExample/languages",
"stargazers_url": "https://api.github.com/repos/traex/RetrofitExample/stargazers",
"contributors_url": "https://api.github.com/repos/traex/RetrofitExample/contributors",
"subscribers_url": "https://api.github.com/repos/traex/RetrofitExample/subscribers",
"subscription_url": "https://api.github.com/repos/traex/RetrofitExample/subscription",
"commits_url": "https://api.github.com/repos/traex/RetrofitExample/commits{/sha}",
"git_commits_url": "https://api.github.com/repos/traex/RetrofitExample/git/commits{/sha}",
"comments_url": "https://api.github.com/repos/traex/RetrofitExample/comments{/number}",
"issue_comment_url": "https://api.github.com/repos/traex/RetrofitExample/issues/comments{/number}",
"contents_url": "https://api.github.com/repos/traex/RetrofitExample/contents/{+path}",
"compare_url": "https://api.github.com/repos/traex/RetrofitExample/compare/{base}...{head}",
"merges_url": "https://api.github.com/repos/traex/RetrofitExample/merges",
"archive_url": "https://api.github.com/repos/traex/RetrofitExample/{archive_format}{/ref}",
"downloads_url": "https://api.github.com/repos/traex/RetrofitExample/downloads",
"issues_url": "https://api.github.com/repos/traex/RetrofitExample/issues{/number}",
"pulls_url": "https://api.github.com/repos/traex/RetrofitExample/pulls{/number}",
"milestones_url": "https://api.github.com/repos/traex/RetrofitExample/milestones{/number}",
"notifications_url": "https://api.github.com/repos/traex/RetrofitExample/notifications{?since,all,participating}",
"labels_url": "https://api.github.com/repos/traex/RetrofitExample/labels{/name}",
"releases_url": "https://api.github.com/repos/traex/RetrofitExample/releases{/id}",
"deployments_url": "https://api.github.com/repos/traex/RetrofitExample/deployments",
"created_at": "2014-10-03T16:50:57Z",
"updated_at": "2019-02-16T12:27:52Z",
"pushed_at": "2015-04-26T19:39:39Z",
"git_url": "git://github.com/traex/RetrofitExample.git",
"ssh_url": "git@github.com:traex/RetrofitExample.git",
"clone_url": "https://github.com/traex/RetrofitExample.git",
"svn_url": "https://github.com/traex/RetrofitExample",
"homepage": null,
"size": 359,
"stargazers_count": 188,
"watchers_count": 188,
"language": "Java",
"has_issues": true,
"has_projects": true,
"has_downloads": true,
"has_wiki": true,
"has_pages": false,
"forks_count": 62,
"mirror_url": null,
"archived": false,
"open_issues_count": 5,
"license": null,
"forks": 62,
"open_issues": 5,
"watchers": 188,
"default_branch": "master",
"score": 92.08982
}
]
}"""

class WebApiUnitTest {

    private val mockServer: MockWebServer = MockWebServer()

    @Before
    fun mockApi() {
        mockServer.start()

        mockkStatic("com.perfect.githubexplorer.data.WebKt")
        every {
            Class.forName("com.perfect.githubexplorer.data.WebKt")
                .getMethod("getGITHUB_BASE_API_URL")
                .invoke(this)
        } returns mockServer.url("/").toString()

    }
//    fun mockApi() {
//        val behavior = NetworkBehavior.create()
//        behavior.setDelay(3.toLong(), TimeUnit.SECONDS)
//        val mockRetrofit = MockRetrofit.Builder(apiRetrofit)
//            .networkBehavior(behavior)
//            .build()
//
//        val delegate = mockRetrofit.create(GithubApiInterface::class.java)
//        val mockApiClient = MockGitHub(delegate)
//
//
//        mockkObject(apiRetrofit)
//
//        every { apiRetrofit.create(GithubApiInterface::class.java) } returns mockApiClient
//
//    }

    @Test
    fun test() {
        mockServer.enqueue(MockResponse().setBody(RESPONSE_JSON))

        val a: SearchRepositoryResponse?
        a = runBlocking {
            apiClient.searchRepositories("salam", 0, 10).await()
        }

        assertEquals(9, a.items.size)
    }

    @After
    fun apiShutdown() {
        mockServer.shutdown()
    }
}
